// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module5_Ord.Models;

#nullable disable

namespace Module5_Ord.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20230216034026_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Module5_Ord.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "685 Kelly St, Queens, NY 11234",
                            Name = "Peter Parker",
                            Note = " ",
                            Phone = "609-773-9847"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "899 Thomas St, Smallville, KS, 68512",
                            Name = "Clark Kent",
                            Note = " ",
                            Phone = "632-555-0108"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "111 America Ln, America, America, 11111",
                            Name = "Steve Rogers",
                            Note = " ",
                            Phone = "678-136-7092"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
